package com.json;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;

/* loaded from: classes4.dex */
public class td {
    public static final String A0 = "diskFreeSize";
    public static final String B0 = "appOrientation";
    public static final String C0 = "asid";
    public static final String D0 = "deviceWidth";
    public static final String E0 = "deviceHeight";
    public static final String F = "auid";
    public static final String F0 = "displaySizeWidth";
    public static final String G0 = "displaySizeHeight";
    public static final String H = "omidV";
    public static final String H0 = "deviceScreenScale";
    public static final String I = "omidPV";
    public static final String I0 = "AID";
    public static final String J = "imm";
    public static final String J0 = "isLimitAdTrackingEnabled";
    public static final String K = "appOr";
    public static final String K0 = "unLocked";
    public static final String L = "sdkV";
    public static final String L0 = "deviceVolume";
    public static final String M0 = "immersiveMode";
    public static final String N = "pType";
    public static final String N0 = "simOperator";
    public static final String O = "simOp";
    public static final String O0 = "phoneType";
    public static final String P = "lUpdateT";
    public static final String P0 = "mcc";
    public static final String Q = "fInstallT";
    public static final String Q0 = "mnc";
    public static final String R = "dSizeW";
    public static final String R0 = "lastUpdateTime";
    public static final String S = "dSizeH";
    public static final String S0 = "appVersion";
    public static final String T = "cellNetT";
    public static final String T0 = "firstInstallTime";
    public static final String U = "vpn";
    public static final String U0 = "batteryLevel";
    public static final String V0 = "consent";
    public static final String W = "sdCrdAvail";
    public static final String W0 = "installerPackageName";
    public static final String X = "isCharge";
    public static final String X0 = "localTime";
    public static final String Y = "chargeT";
    public static final String Y0 = "clientTimestamp";
    public static final String Z = "airM";
    public static final String Z0 = "timezoneOffset";
    public static final String a0 = "onWhnPlugIn";
    public static final String a1 = "sdCardAvailable";
    public static final String b0 = "dRAM";
    public static final String b1 = "totalDeviceRAM";
    public static final String c = "appKey";
    public static final String c0 = "iPckgN";
    public static final String c1 = "isCharging";
    public static final String d0 = "tzOff";
    public static final String d1 = "chargingType";
    public static final String e0 = "cnaCDN";
    public static final String e1 = "airplaneMode";
    public static final String f0 = "applicationUserId";
    public static final String f1 = "stayOnWhenPluggedIn";
    public static final String g0 = "applicationKey";
    public static final String g1 = "SDKPluginType";
    public static final String h0 = "sessionDepthRV";
    public static final String h1 = "advertisingId";
    public static final String i0 = "sessionDepthIS";
    public static final String i1 = "advIdType";
    public static final String j0 = "sessionId";
    public static final String j1 = "applicationUserGender";
    public static final String k0 = "deviceOEM";
    public static final String k1 = "applicationUserAge";
    public static final String l0 = "deviceModel";
    public static final String l1 = "metadata";
    public static final String m0 = "deviceMake";
    public static final String m1 = "bundleId";
    public static final String n0 = "deviceIds[AID]";
    public static final String n1 = "omidVersion";
    public static final String o0 = "deviceOs";
    public static final String o1 = "omidPartnerVersion";
    public static final String p0 = "deviceOS";
    public static final String p1 = "chinaCDN";
    public static final String q0 = "deviceOSVersion";
    public static final String r0 = "deviceOSVersionFull";
    public static final String r1 = "metadata_";
    public static final String s0 = "deviceApiLevel";
    private static final String s1 = "Gpi";
    public static final String t0 = "SDKVersion";
    private static final String t1 = "blacklistedCampaigns";
    public static final String u0 = "MedSDKVersion";
    private static final String u1 = "biddingRVImpressions";
    public static final String v0 = "mobileCarrier";
    private static final String v1 = "biddingISImpressions";
    public static final String w = "bat";
    public static final String w0 = "connectionType";
    private static final String w1 = "totalRVSessionImpressions";
    public static final String x = "lpm";
    public static final String x0 = "cellularNetworkType";
    private static final String x1 = "totalISSessionImpressions";
    public static final String y0 = "hasVPN";
    public static final String z0 = "deviceLanguage";
    public static final String q1 = "applicationUserAgeGroup";

    /* renamed from: a, reason: collision with root package name */
    public static final String f2313a = "uAge";
    public static final String b = "advId";
    public static final String d = "mCar";
    public static final String e = "medV";
    public static final String f = "connT";
    public static final String g = "dWidth";
    public static final String h = "dHeight";
    public static final String i = "dModel";
    public static final String j = "cTime";
    public static final String k = "sDepRV";
    public static final String l = "sDepIS";
    public static final String m = "sId";
    public static final String n = "plType";
    public static final String o = "dOSV";
    public static final String p = "dOSVF";
    public static final String q = "dOS";
    public static final String r = "dMake";
    public static final String s = "dAPI";
    public static final String t = "bId";
    public static final String u = "appV";
    public static final String v = "usId";
    public static final String y = "root";
    public static final String z = "diskFS";
    public static final String A = "dLang";
    public static final String B = "MD";
    public static final String C = "uGen";
    public static final String D = "advType";
    public static final String E = "isLAT";
    public static final String V = "dVol";
    public static final String M = "dScrenScle";
    public static final String G = "UA";
    public static final ArrayList<String> y1 = new ArrayList<>(Arrays.asList(q1, f2313a, b, "appKey", d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, "bat", y, z, A, B, C, D, E, V, "consent", h, g, M, "auid", G, "asid"));
    public static final HashMap<String, String> z1 = new a();

    class a extends HashMap<String, String> {
        a() {
            put("omidVersion", td.H);
            put("omidPartnerVersion", td.I);
            put("immersiveMode", "imm");
            put("appOrientation", td.K);
            put("SDKVersion", td.L);
            put("deviceScreenScale", td.M);
            put("phoneType", td.N);
            put("simOperator", td.O);
            put("lastUpdateTime", td.P);
            put("firstInstallTime", td.Q);
            put("displaySizeWidth", td.g);
            put("displaySizeHeight", td.h);
            put(td.x0, td.T);
            put("hasVPN", "vpn");
            put("deviceVolume", td.V);
            put("sdCardAvailable", td.W);
            put("isCharging", td.X);
            put("chargingType", td.Y);
            put("airplaneMode", td.Z);
            put("stayOnWhenPluggedIn", td.a0);
            put("totalDeviceRAM", td.b0);
            put("installerPackageName", td.c0);
            put("timezoneOffset", td.d0);
            put("chinaCDN", td.e0);
            put("deviceOs", td.q);
            put("localTime", td.j);
            put(td.n0, td.b);
            put(td.k1, td.f2313a);
            put(td.h1, td.b);
            put(td.i1, td.D);
            put(td.D0, td.g);
            put(td.E0, td.h);
            put(td.p0, td.q);
            put(td.Y0, td.j);
            put(td.h0, td.k);
            put(td.i0, td.l);
            put("sessionId", td.m);
            put(td.u0, td.e);
            put(td.m0, td.r);
            put(td.j1, td.C);
            put("batteryLevel", "bat");
            put("unLocked", td.y);
            put("deviceOSVersion", td.o);
            put("bundleId", td.t);
            put("mobileCarrier", td.d);
            put("connectionType", td.f);
            put("appVersion", td.u);
            put("applicationKey", "appKey");
            put("applicationUserId", td.v);
            put("isLimitAdTrackingEnabled", td.E);
            put("metadata", td.B);
            put("deviceModel", td.i);
            put(td.g1, td.n);
            put("deviceApiLevel", td.s);
            put("diskFreeSize", td.z);
            put("deviceLanguage", td.A);
            put("deviceOEM", td.r);
            put("deviceOSVersionFull", td.p);
        }
    }
}
