package com.applovin.impl;

import android.net.Uri;
import com.applovin.impl.adview.AppLovinTouchToClickListener;
import com.applovin.impl.qi;
import com.applovin.mediation.MaxAdFormat;
import com.applovin.sdk.AppLovinAdSize;
import com.google.android.exoplayer2.C;
import com.google.android.exoplayer2.audio.AacUtil;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.TimeUnit;

/* loaded from: classes.dex */
public class oj implements Comparable {
    public static final oj A;
    public static final oj A0;
    public static final oj A1;
    public static final oj A2;
    public static final oj A3;
    public static final oj A4;
    public static final oj A5;
    public static final oj A6;
    public static final oj B;
    public static final oj B0;
    public static final oj B1;
    public static final oj B2;
    public static final oj B3;
    public static final oj B4;
    public static final oj B5;
    public static final oj B6;
    public static final oj C;
    public static final oj C0;
    public static final oj C1;
    public static final oj C2;
    public static final oj C3;
    public static final oj C4;
    public static final oj C5;
    public static final oj C6;
    public static final oj D;
    public static final oj D0;
    public static final oj D1;
    public static final oj D2;
    public static final oj D3;
    public static final oj D4;
    public static final oj D5;
    public static final oj D6;
    public static final oj E;
    public static final oj E0;
    public static final oj E1;
    public static final oj E2;
    public static final oj E3;
    public static final oj E4;
    public static final oj E5;
    public static final oj E6;
    public static final oj F;
    public static final oj F0;
    public static final oj F1;
    public static final oj F2;
    public static final oj F3;
    public static final oj F4;
    public static final oj F5;
    public static final oj F6;
    public static final oj G;
    public static final oj G0;
    public static final oj G1;
    public static final oj G2;
    public static final oj G3;
    public static final oj G4;
    public static final oj G5;
    public static final oj H;
    public static final oj H0;
    public static final oj H1;
    public static final oj H2;
    public static final oj H3;
    public static final oj H4;
    public static final oj H5;
    public static final oj I;
    public static final oj I0;
    public static final oj I1;
    public static final oj I2;
    public static final oj I3;
    public static final oj I4;
    public static final oj I5;
    public static final oj J;
    public static final oj J0;
    public static final oj J1;
    public static final oj J2;
    public static final oj J3;
    public static final oj J4;
    public static final oj J5;
    public static final oj K;
    public static final oj K0;
    public static final oj K1;
    public static final oj K2;
    public static final oj K3;
    public static final oj K4;
    public static final oj K5;
    public static final oj L;
    public static final oj L0;
    public static final oj L1;
    public static final oj L2;
    public static final oj L3;
    public static final oj L4;
    public static final oj L5;
    public static final oj M;
    public static final oj M0;
    public static final oj M1;
    public static final oj M2;
    public static final oj M3;
    public static final oj M4;
    public static final oj M5;
    public static final oj N;
    public static final oj N0;
    public static final oj N1;
    public static final oj N2;
    public static final oj N3;
    public static final oj N4;
    public static final oj N5;
    public static final oj O;
    public static final oj O0;
    public static final oj O1;
    public static final oj O2;
    public static final oj O3;
    public static final oj O4;
    public static final oj O5;
    public static final oj P;
    public static final oj P0;
    public static final oj P1;
    public static final oj P2;
    public static final oj P3;
    public static final oj P4;
    public static final oj P5;
    public static final oj Q;
    public static final oj Q0;
    public static final oj Q1;
    public static final oj Q2;
    public static final oj Q3;
    public static final oj Q4;
    public static final oj Q5;
    public static final oj R;
    public static final oj R0;
    public static final oj R1;
    public static final oj R2;
    public static final oj R3;
    public static final oj R4;
    public static final oj R5;
    public static final oj S;
    public static final oj S0;
    public static final oj S1;
    public static final oj S2;
    public static final oj S3;
    public static final oj S4;
    public static final oj S5;
    public static final oj T;
    public static final oj T0;
    public static final oj T1;
    public static final oj T2;
    public static final oj T3;
    public static final oj T4;
    public static final oj T5;
    public static final oj U;
    public static final oj U0;
    public static final oj U1;
    public static final oj U2;
    public static final oj U3;
    public static final oj U4;
    public static final oj U5;
    public static final oj V;
    public static final oj V0;
    public static final oj V1;
    public static final oj V2;
    public static final oj V3;
    public static final oj V4;
    public static final oj V5;
    public static final oj W;
    public static final oj W0;
    public static final oj W1;
    public static final oj W2;
    public static final oj W3;
    public static final oj W4;
    public static final oj W5;
    public static final oj X;
    public static final oj X0;
    public static final oj X1;
    public static final oj X2;
    public static final oj X3;
    public static final oj X4;
    public static final oj X5;
    public static final oj Y;
    public static final oj Y0;
    public static final oj Y1;
    public static final oj Y2;
    public static final oj Y3;
    public static final oj Y4;
    public static final oj Y5;
    public static final oj Z;
    public static final oj Z0;
    public static final oj Z1;
    public static final oj Z2;
    public static final oj Z3;
    public static final oj Z4;
    public static final oj Z5;
    public static final oj a0;
    public static final oj a1;
    public static final oj a2;
    public static final oj a3;
    public static final oj a4;
    public static final oj a5;
    public static final oj a6;
    public static final oj b0;
    public static final oj b1;
    public static final oj b2;
    public static final oj b3;
    public static final oj b4;
    public static final oj b5;
    public static final oj b6;
    public static final oj c0;
    public static final oj c1;
    public static final oj c2;
    public static final oj c3;
    public static final oj c4;
    public static final oj c5;
    public static final oj c6;
    public static final oj d0;
    public static final oj d1;
    public static final oj d2;
    public static final oj d3;
    public static final oj d4;
    public static final oj d5;
    public static final oj d6;
    public static final oj e0;
    public static final oj e1;
    public static final oj e2;
    public static final oj e3;
    public static final oj e4;
    public static final oj e5;
    public static final oj e6;
    public static final oj f;
    public static final oj f0;
    public static final oj f1;
    public static final oj f2;
    public static final oj f3;
    public static final oj f4;
    public static final oj f5;
    public static final oj f6;
    public static final oj g;
    public static final oj g0;
    public static final oj g1;
    public static final oj g2;
    public static final oj g3;
    public static final oj g4;
    public static final oj g5;
    public static final oj g6;
    public static final oj h;
    public static final oj h0;
    public static final oj h1;
    public static final oj h2;
    public static final oj h3;
    public static final oj h4;
    public static final oj h5;
    public static final oj h6;
    public static final oj i;
    public static final oj i0;
    public static final oj i1;
    public static final oj i2;
    public static final oj i3;
    public static final oj i4;
    public static final oj i5;
    public static final oj i6;
    public static final oj j;
    public static final oj j0;
    public static final oj j1;
    public static final oj j2;
    public static final oj j3;
    public static final oj j4;
    public static final oj j5;
    public static final oj j6;
    public static final oj k;
    public static final oj k0;
    public static final oj k1;
    public static final oj k2;
    public static final oj k3;
    public static final oj k4;
    public static final oj k5;
    public static final oj k6;
    public static final oj l;
    public static final oj l0;
    public static final oj l1;
    public static final oj l2;
    public static final oj l3;
    public static final oj l4;
    public static final oj l5;
    public static final oj l6;
    public static final oj m;
    public static final oj m0;
    public static final oj m1;
    public static final oj m2;
    public static final oj m3;
    public static final oj m4;
    public static final oj m5;
    public static final oj m6;
    public static final oj n;
    public static final oj n0;
    public static final oj n1;
    public static final oj n2;
    public static final oj n3;
    public static final oj n4;
    public static final oj n5;
    public static final oj n6;
    public static final oj o;
    public static final oj o0;
    public static final oj o1;
    public static final oj o2;
    public static final oj o3;
    public static final oj o4;
    public static final oj o5;
    public static final oj o6;
    public static final oj p;
    public static final oj p0;
    public static final oj p1;
    public static final oj p2;
    public static final oj p3;
    public static final oj p4;
    public static final oj p5;
    public static final oj p6;
    public static final oj q;
    public static final oj q0;
    public static final oj q1;
    public static final oj q2;
    public static final oj q3;
    public static final oj q4;
    public static final oj q5;
    public static final oj q6;
    public static final oj r;
    public static final oj r0;
    public static final oj r1;
    public static final oj r2;
    public static final oj r3;
    public static final oj r4;
    public static final oj r5;
    public static final oj r6;
    public static final oj s;
    public static final oj s0;
    public static final oj s1;
    public static final oj s2;
    public static final oj s3;
    public static final oj s4;
    public static final oj s5;
    public static final oj s6;
    public static final oj t;
    public static final oj t0;
    public static final oj t1;
    public static final oj t2;
    public static final oj t3;
    public static final oj t4;
    public static final oj t5;
    public static final oj t6;
    public static final oj u;
    public static final oj u0;
    public static final oj u1;
    public static final oj u2;
    public static final oj u3;
    public static final oj u4;
    public static final oj u5;
    public static final oj u6;
    public static final oj v;
    public static final oj v0;
    public static final oj v1;
    public static final oj v2;
    public static final oj v3;
    public static final oj v4;
    public static final oj v5;
    public static final oj v6;
    public static final oj w;
    public static final oj w0;
    public static final oj w1;
    public static final oj w2;
    public static final oj w3;
    public static final oj w4;
    public static final oj w5;
    public static final oj w6;
    public static final oj x;
    public static final oj x0;
    public static final oj x1;
    public static final oj x2;
    public static final oj x3;
    public static final oj x4;
    public static final oj x5;
    public static final oj x6;
    public static final oj y;
    public static final oj y0;
    public static final oj y1;
    public static final oj y2;
    public static final oj y3;
    public static final oj y4;
    public static final oj y5;
    public static final oj y6;
    public static final oj z;
    public static final oj z0;
    public static final oj z1;
    public static final oj z2;
    public static final oj z3;
    public static final oj z4;
    public static final oj z5;
    public static final oj z6;

    /* renamed from: a, reason: collision with root package name */
    private final String f760a;
    private final Object b;
    private static final List c = Arrays.asList(Boolean.class, Float.class, Integer.class, Long.class, String.class);
    private static final Map d = new HashMap(512);

    public static Collection c() {
        return Collections.synchronizedCollection(d.values());
    }

    static {
        Boolean bool = Boolean.FALSE;
        f = a("is_disabled", bool);
        g = a("device_id", "");
        Boolean bool2 = Boolean.TRUE;
        h = a("rss", bool2);
        i = a("rssoitf", bool);
        j = a("cpoitf", bool);
        k = a("device_token", "");
        l = a("is_verbose_logging", bool);
        m = a("error_reporter_v1_sample_percent", 100);
        n = a("error_reporter_v2", bool);
        o = a("error_reporter_v2_sample_percent", 1);
        p = a("error_reporter_v2_endpoint", "https://docs.applovin.com/1.0/sdk/event");
        q = a("sc", "");
        r = a("sc2", "");
        s = a("sc3", "");
        t = a("server_installed_at", "");
        u = a("pnrc", bool);
        v = a("clear_completion_callback_on_failure", bool);
        w = a("sicd_ms", 0L);
        x = a("logcat_max_line_size", 1000);
        y = a("exception_handler_enabled", bool2);
        z = a("aei", -1);
        A = a("mei", -1);
        B = a(com.json.i5.r, "");
        C = a("bdae", bool);
        D = a("tewllm", bool2);
        E = a("tewplosda", bool2);
        F = a("srwbe", bool);
        G = a("malaera", -1);
        H = a("eralaf", "");
        I = a("eraziie", bool);
        J = a("ps_atu", "");
        K = a("lsu", bool);
        L = a("tla_ms", -1L);
        M = a("stwr", bool);
        N = a("uactlac", bool);
        O = a("stps", 2);
        P = a("auxiliary_operations_threads", 1);
        Q = a("apsobt", bool2);
        R = a("tmtp", 1);
        S = a("network_thread_count", 2);
        T = a("ntp", 5);
        U = a("ueq", bool);
        V = a("coretc", 1);
        W = a("cachetc", 1);
        X = a("mtc", 1);
        Y = a("ttc", 1);
        Z = a("otc", 1);
        a0 = a("uaeq", bool);
        b0 = a("ah_cvc", bool2);
        c0 = a("ah_cdde", bool2);
        d0 = a("ah_crut", bool2);
        e0 = a("init_omsdk", bool2);
        f0 = a("omsdk_partner_name", "applovin");
        g0 = a("publisher_can_show_consent_dialog", bool2);
        h0 = a("consent_dialog_url", "https://assets.applovin.com/gdpr/flow_v1/gdpr-flow-1.html");
        i0 = a("consent_dialog_immersive_mode_on", bool);
        j0 = a("consent_dialog_show_from_alert_delay_ms", 450L);
        k0 = a("alert_consent_for_dialog_rejected", bool);
        l0 = a("alert_consent_for_dialog_closed", bool);
        m0 = a("alert_consent_for_dialog_closed_with_back_button", bool);
        n0 = a("alert_consent_after_init", bool);
        TimeUnit timeUnit = TimeUnit.MINUTES;
        o0 = a("alert_consent_after_init_interval_ms", Long.valueOf(timeUnit.toMillis(5L)));
        p0 = a("alert_consent_after_dialog_rejection_interval_ms", Long.valueOf(timeUnit.toMillis(30L)));
        q0 = a("alert_consent_after_dialog_close_interval_ms", Long.valueOf(timeUnit.toMillis(5L)));
        r0 = a("alert_consent_after_dialog_close_with_back_button_interval_ms", Long.valueOf(timeUnit.toMillis(5L)));
        s0 = a("alert_consent_after_cancel_interval_ms", Long.valueOf(timeUnit.toMillis(10L)));
        t0 = a("alert_consent_reschedule_interval_ms", Long.valueOf(timeUnit.toMillis(5L)));
        u0 = a("text_alert_consent_title", "Make this App Better and Stay Free!");
        v0 = a("text_alert_consent_body", "If you don't give us consent to use your data, you will be making our ability to support this app harder, which may negatively affect the user experience.");
        w0 = a("text_alert_consent_yes_option", "I Agree");
        x0 = a("text_alert_consent_no_option", "Cancel");
        TimeUnit timeUnit2 = TimeUnit.SECONDS;
        y0 = a("ttc_max_click_duration_ms", Long.valueOf(timeUnit2.toMillis(1L)));
        z0 = a("ttc_max_click_distance_dp", 10);
        AppLovinTouchToClickListener.ClickRecognitionState clickRecognitionState = AppLovinTouchToClickListener.ClickRecognitionState.ACTION_DOWN;
        A0 = a("ttc_acrsv2a", Integer.valueOf(clickRecognitionState.ordinal()));
        B0 = a("ttc_acrsnv", Integer.valueOf(clickRecognitionState.ordinal()));
        C0 = a("ttc_acrsa", Integer.valueOf(clickRecognitionState.ordinal()));
        D0 = a("ttc_acrsn", Integer.valueOf(clickRecognitionState.ordinal()));
        E0 = a("ttc_edge_buffer_dp", 0);
        F0 = a("whitelisted_postback_endpoints", "https://prod-a.applovin.com,https://rt.applovin.com/4.0/pix, https://rt.applvn.com/4.0/pix,https://ms.applovin.com/,https://ms.applvn.com/");
        G0 = a("fetch_settings_endpoint", "https://ms.applovin.com/");
        H0 = a("fetch_settings_backup_endpoint", "https://ms.applvn.com/");
        I0 = a("adserver_endpoint", "https://a.applovin.com/");
        J0 = a("adserver_backup_endpoint", "https://a.applvn.com/");
        K0 = a("api_endpoint", "https://d.applovin.com/");
        L0 = a("api_backup_endpoint", "https://d.applvn.com/");
        M0 = a("event_tracking_endpoint_v2", "https://rt.applovin.com/");
        N0 = a("event_tracking_backup_endpoint_v2", "https://rt.applvn.com/");
        O0 = a("token_type_prefixes_r", "4!");
        P0 = a("token_type_prefixes_arj", "json_v3!");
        Q0 = a("top_level_events", "landing,paused,resumed,cf_start,tos_ok,gdpr_ok,ref,rdf,checkout,iap");
        R0 = a("valid_super_property_types", String.class.getName() + "," + Integer.class.getName() + "," + Long.class.getName() + "," + Double.class.getName() + "," + Float.class.getName() + "," + Date.class.getName() + "," + Uri.class.getName() + "," + List.class.getName() + "," + Map.class.getName());
        S0 = a("persist_super_properties", bool2);
        T0 = a("super_property_string_max_length", 1024);
        U0 = a("super_property_url_max_length", 1024);
        TimeUnit timeUnit3 = TimeUnit.DAYS;
        V0 = a("cache_file_ttl_seconds", Long.valueOf(timeUnit3.toSeconds(1L)));
        W0 = a("cache_max_size_mb", -1);
        X0 = a("precache_delimiters", ")]', ");
        Y0 = a("ad_resource_caching_enabled", bool2);
        Z0 = a("resource_cache_prefix", "https://vid.applovin.com/,https://stage-vid.applovin.com/,https://pdn.applovin.com/,https://stage-pdn.applovin.com/,https://img.applovin.com/,https://stage-img.applovin.com/,https://d.applovin.com/,https://assets.applovin.com/,https://stage-assets.applovin.com/,https://cdnjs.cloudflare.com/,http://vid.applovin.com/,http://stage-vid.applovin.com/,http://pdn.applovin.com/,http://stage-pdn.applovin.com/,http://img.applovin.com/,http://stage-img.applovin.com/,http://d.applovin.com/,http://assets.applovin.com/,http://stage-assets.applovin.com/,http://cdnjs.cloudflare.com/,http://u.appl.vn/,https://u.appl.vn/,https://res.applovin.com/,https://res1.applovin.com/,https://res2.applovin.com/,https://res3.applovin.com/,http://res.applovin.com/,http://res1.applovin.com/,http://res2.applovin.com/,http://res3.applovin.com/");
        a1 = a("preserved_cached_assets", "sound_off.png,sound_on.png,closeOptOut.png,1381250003_28x28.png,zepto-1.1.3.min.js,jquery-2.1.1.min.js,jquery-1.9.1.min.js,jquery.knob.js");
        b1 = a("resource_max_filename_length", 255);
        c1 = a("ccrc", bool);
        d1 = a("mcct", 3);
        e1 = a("mchct", 3);
        f1 = a("dficf", bool);
        g1 = a("dfirf", bool);
        h1 = a("dfipf", bool);
        i1 = a("decr", bool);
        j1 = a("dcrome", bool);
        k1 = a("dcrobs", bool);
        l1 = a("lfeufc", bool);
        m1 = a("pcro", bool);
        n1 = a("efecobt", bool);
        o1 = a("saewib", bool);
        p1 = a("fsae_ms", -1L);
        q1 = a("raae", bool);
        r1 = a("vr_retry_count_v1", 1);
        s1 = a("cr_retry_count_v1", 1);
        t1 = a("text_incent_warning_title", "Attention!");
        u1 = a("text_incent_warning_body", "You won’t get your reward if the video hasn’t finished.");
        v1 = a("text_incent_warning_close_option", "Close");
        w1 = a("text_incent_warning_continue_option", "Keep Watching");
        x1 = a("text_incent_nonvideo_warning_title", "Attention!");
        y1 = a("text_incent_nonvideo_warning_body", "You won’t get your reward if the game hasn’t finished.");
        z1 = a("text_incent_nonvideo_warning_close_option", "Close");
        A1 = a("text_incent_nonvideo_warning_continue_option", "Keep Playing");
        B1 = a("close_button_touch_area", 0);
        C1 = a("close_button_outside_touch_area", 0);
        D1 = a("creative_debugger_enabled", bool2);
        E1 = a("smdfhcdb", bool2);
        F1 = a("adview_clearview", bool);
        G1 = a("ravip", bool);
        H1 = a("viewability_adview_imp_delay_ms", Long.valueOf(timeUnit2.toMillis(1L)));
        I1 = a("viewability_adview_banner_min_width", 320);
        J1 = a("viewability_adview_banner_min_height", Integer.valueOf(AppLovinAdSize.BANNER.getHeight()));
        MaxAdFormat maxAdFormat = MaxAdFormat.MREC;
        K1 = a("viewability_adview_mrec_min_width", Integer.valueOf(maxAdFormat.getSize().getWidth()));
        L1 = a("viewability_adview_mrec_min_height", Integer.valueOf(maxAdFormat.getSize().getHeight()));
        M1 = a("viewability_adview_leader_min_width", 728);
        N1 = a("viewability_adview_leader_min_height", Integer.valueOf(AppLovinAdSize.LEADER.getHeight()));
        O1 = a("viewability_adview_native_min_width", 0);
        P1 = a("viewability_adview_native_min_height", 0);
        Q1 = a("viewability_adview_min_alpha", Float.valueOf(10.0f));
        R1 = a("viewability_timer_min_visible_ms", Long.valueOf(timeUnit2.toMillis(1L)));
        S1 = a("viewability_timer_interval_ms", 100L);
        T1 = a("expandable_close_button_size", 27);
        U1 = a("expandable_h_close_button_margin", 10);
        V1 = a("expandable_t_close_button_margin", 10);
        W1 = a("expandable_lhs_close_button", bool);
        X1 = a("expandable_close_button_touch_area", 0);
        Y1 = a("iaad", bool);
        Z1 = a("js_tag_schemes", "applovin,mopub");
        a2 = a("js_tag_load_success_hosts", "load,load_succeeded");
        b2 = a("js_tag_load_failure_hosts", "failLoad,load_failed");
        c2 = a("fullscreen_ad_pending_display_state_timeout_ms", Long.valueOf(timeUnit2.toMillis(10L)));
        d2 = a("fullscreen_ad_showing_state_timeout_ms", Long.valueOf(timeUnit.toMillis(2L)));
        e2 = a("lhs_close_button_video", bool);
        f2 = a("close_button_right_margin_video", 4);
        g2 = a("close_button_size_video", 30);
        h2 = a("close_button_top_margin_video", 8);
        i2 = a("video_countdown_clock_margin", 10);
        j2 = a("video_countdown_clock_gravity", 83);
        k2 = a("countdown_clock_size", 32);
        l2 = a("countdown_clock_stroke_size", 4);
        m2 = a("countdown_clock_text_size", 28);
        n2 = a("draw_countdown_clock", bool2);
        o2 = a("inter_display_delay", 200L);
        p2 = a("maximum_close_button_delay_seconds", 999L);
        q2 = a("respect_close_button", bool2);
        r2 = a("lhs_skip_button", bool2);
        s2 = a("track_app_killed", bool);
        t2 = a("app_closed_time_threshold_for_app_killed_event_ms", Long.valueOf(timeUnit2.toMillis(60L)));
        u2 = a("mute_controls_enabled", bool);
        v2 = a("allow_user_muting", bool2);
        w2 = a("mute_videos", bool);
        x2 = a("show_mute_by_default", bool);
        y2 = a("mute_with_user_settings", bool2);
        z2 = a("mute_button_size", 32);
        A2 = a("mute_button_margin", 10);
        B2 = a("mute_button_gravity", 85);
        C2 = a("progress_bar_step", 25L);
        D2 = a("progress_bar_scale", 10000);
        E2 = a("progress_bar_vertical_padding", -8);
        F2 = a("vs_buffer_indicator_size", 50);
        G2 = a("video_zero_length_as_computed", bool);
        H2 = a("set_poststitial_muted_initial_delay_ms", 500L);
        I2 = a("fasuic", bool2);
        J2 = a("fsahrpg", bool2);
        K2 = a("eaafrwsoa", bool2);
        L2 = a("postitial_progress_bar_step_ms", 25L);
        M2 = a("postitial_progress_bar_on_bottom", bool2);
        N2 = a("postitial_progress_bar_vertical_padding", -8);
        O2 = a("postitial_progress_bar_scale", 10000);
        P2 = a("fahosu", bool);
        Q2 = a("pause_fullscreen_ad_ui_when_app_is_backgrounded", bool);
        R2 = a("forward_javascript_to_webview_video_button", bool);
        S2 = a("nsuttcl", bool);
        T2 = a("submit_postback_timeout", Integer.valueOf((int) timeUnit2.toMillis(10L)));
        U2 = a("submit_postback_retries", 4);
        V2 = a("max_postback_attempts", 3);
        W2 = a("max_persisted_postbacks", 100);
        X2 = a("submit_web_tracker_timeout", Integer.valueOf((int) timeUnit2.toMillis(7L)));
        Y2 = a("sossp", bool);
        Z2 = a("spp", bool2);
        a3 = a("get_retry_delay_v1", Integer.valueOf((int) timeUnit2.toMillis(10L)));
        b3 = a("http_connection_timeout", Integer.valueOf((int) timeUnit2.toMillis(30L)));
        c3 = a("http_socket_timeout", Integer.valueOf((int) timeUnit2.toMillis(20L)));
        d3 = a("force_ssl", bool);
        e3 = a("fetch_ad_connection_timeout", Integer.valueOf((int) timeUnit2.toMillis(30L)));
        f3 = a("fetch_ad_retry_count_v1", 1);
        g3 = a("faer", bool);
        h3 = a("faroae", bool);
        i3 = a("submit_data_retry_count_v1", 1);
        j3 = a("response_buffer_size", Integer.valueOf(AacUtil.AAC_HE_V1_MAX_RATE_BYTES_PER_SECOND));
        k3 = a("fetch_basic_settings_connection_timeout_ms", Integer.valueOf((int) timeUnit2.toMillis(10L)));
        l3 = a("fetch_basic_settings_retry_count", 3);
        m3 = a("fetch_basic_settings_on_reconnect", bool);
        n3 = a("skip_fetch_basic_settings_if_not_connected", bool);
        o3 = a("fetch_basic_settings_retry_delay_ms", Integer.valueOf((int) timeUnit2.toMillis(2L)));
        p3 = a("idflrwbe", bool);
        q3 = a("falawpr", bool);
        r3 = a("sort_query_parameters", bool);
        s3 = a("communicator_request_timeout_ms", Long.valueOf(timeUnit2.toMillis(10L)));
        t3 = a("communicator_request_retry_count", 3);
        u3 = a("communicator_request_retry_delay_ms", Long.valueOf(timeUnit2.toMillis(2L)));
        v3 = a("rfbsd_ms", -1L);
        w3 = a("ehkpd_ms", 500L);
        x3 = a("rironc", bool);
        y3 = a("rroncbd", bool);
        z3 = a("wverc_ms", Long.valueOf(timeUnit2.toMillis(5L)));
        A3 = a("sducifm", bool);
        B3 = a("ad_session_minutes", 60);
        C3 = a("session_tracking_cooldown_on_event_fire", bool2);
        D3 = a("session_tracking_resumed_cooldown_minutes", 90L);
        E3 = a("session_tracking_paused_cooldown_minutes", 90L);
        F3 = a("dc_v2", bool);
        G3 = a("dce", bool2);
        H3 = a("qq", bool);
        I3 = a("qq1", bool2);
        J3 = a("qq2", bool2);
        K3 = a("qq3", bool2);
        L3 = a("qq4", bool2);
        M3 = a("qq5", bool2);
        N3 = a("qq6", bool2);
        O3 = a("qq7", bool2);
        P3 = a("qq8", bool2);
        Q3 = a("qq9", bool);
        R3 = a("qq10", bool2);
        S3 = a("qq11", bool2);
        T3 = a("pui", bool2);
        U3 = a("plugin_version", "");
        V3 = a("ccbtbsic", bool);
        W3 = a("hgn", bool2);
        X3 = a("cso", bool2);
        Y3 = a("cfs", bool2);
        Z3 = a("cmi", bool2);
        a4 = a("crat", bool2);
        b4 = a("cvs", bool2);
        c4 = a("caf", bool2);
        d4 = a("cf", bool2);
        e4 = a("cmtl", bool2);
        f4 = a("cnr", bool2);
        g4 = a("ccr", bool);
        h4 = a("adr", bool2);
        i4 = a("volume_normalization_factor", Float.valueOf(6.6666665f));
        j4 = a("system_user_agent_collection_enabled", bool);
        k4 = a("user_agent_collection_enabled", bool);
        l4 = a("collect_device_angle", bool2);
        m4 = a("collect_device_movement", bool2);
        n4 = a("cipc", bool2);
        o4 = a("movement_degradation", Float.valueOf(0.75f));
        p4 = a("device_sensor_period_ms", 250);
        q4 = a("idcw", bool);
        r4 = a("fetch_basic_settings_delay_ms", 1500);
        s4 = a("mps", "");
        t4 = a("mpsl", 3);
        u4 = a("mpis", "com.applovin,dalvik,java,android,com.android");
        v4 = a("cmps", bool);
        w4 = a("rmps", bool);
        x4 = a("collect_webview_package_info", bool);
        y4 = a("webview_package_names", "com.google.android.webview,com.android.webview");
        z4 = a("collect_opengl_version", bool);
        A4 = a("ncre", bool);
        B4 = a("ncrs", "4,5,6,7,8,11,16");
        C4 = a("dcttl_1_seconds", 5);
        D4 = a("dcttl_2_seconds", 30);
        E4 = a("dcttl_3_seconds", Integer.valueOf((int) timeUnit.toSeconds(1L)));
        F4 = a("dcttl_4_seconds", Integer.valueOf((int) timeUnit.toSeconds(30L)));
        G4 = a("dcttl_5_seconds", Integer.valueOf((int) TimeUnit.HOURS.toSeconds(1L)));
        H4 = a("dcttl_6_seconds", Integer.valueOf((int) timeUnit3.toSeconds(1L)));
        I4 = a("cclia", bool2);
        J4 = a("lccdm", 10L);
        K4 = a("lmfd", 2);
        L4 = a("is_track_ad_info", bool2);
        M4 = a("umsm", bool);
        N4 = a("vast_image_html", "<html><head><style>html,body{height:100%;width:100%}body{background-image:url({SOURCE});background-repeat:no-repeat;background-size:contain;background-position:center;}a{position:absolute;top:0;bottom:0;left:0;right:0}</style></head><body><a href=\"applovin://com.applovin.sdk/adservice/track_click_now\"></a></body></html>");
        O4 = a("vast_link_html", "<html><head><style>html,body,iframe{height:100%;width:100%;}body{margin:0}iframe{border:0;overflow:hidden;position:absolute}</style></head><body><iframe src={SOURCE} frameborder=0></iframe></body></html>");
        P4 = a("vast_max_response_length", 640000);
        Q4 = a("vast_max_wrapper_depth", 5);
        R4 = a("vast_unsupported_video_extensions", "ogv,flv");
        S4 = a("vast_unsupported_video_types", "video/ogg,video/x-flv");
        T4 = a("vast_validate_with_extension_if_no_video_type", bool2);
        U4 = a("vast_wrapper_resolution_retry_count_v1", 1);
        V4 = a("vast_wrapper_resolution_connection_timeout", Integer.valueOf((int) timeUnit2.toMillis(30L)));
        W4 = a("vast_industry_icon_max_size", 20);
        X4 = a("vast_industry_icon_margin", 12);
        Y4 = a("vast_industry_icon_gravity", 85);
        Z4 = a("vast_native_mute_button_size", 24);
        a5 = a("vast_native_play_pause_button_size", 24);
        b5 = a("vast_native_video_widget_padding", 6);
        c5 = a("vast_native_video_widget_alpha", Float.valueOf(0.5f));
        d5 = a("vast_native_video_widgets_enabled", bool2);
        e5 = a("vast_replay_video_upon_completion", bool2);
        f5 = a("vast_replay_icon_size", 64);
        g5 = a("vcjfhr", bool);
        h5 = a("vcjfhrr", "(?:<|%3C)script[^>]*src=\"(https[^\"]*\\.js[^\"]*)\".*?(?:>|%3E)");
        i5 = a("vpenfxr", "(<Error><!\\[CDATA\\[[^>]*><\\/Error>)");
        j5 = a("ree", bool2);
        qi.a aVar = qi.a.DEFAULT;
        k5 = a("ree_t", Integer.valueOf(aVar.b()));
        l5 = a("btee", bool2);
        m5 = a("btet", Integer.valueOf(aVar.b()));
        n5 = a("reetoa", bool);
        o5 = a("reet_msfs", Integer.valueOf(aVar.b()));
        p5 = a("reet_msma", Integer.valueOf(qi.a.V2.b()));
        q5 = a("reet_msmd", Integer.valueOf(aVar.b()));
        r5 = a("reet_asfp", Integer.valueOf(aVar.b()));
        s5 = a("reet_asfg", Integer.valueOf(aVar.b()));
        t5 = a("reet_aset", Integer.valueOf(aVar.b()));
        u5 = a("reet_esdi", Integer.valueOf(aVar.b()));
        v5 = a("reet_esrp", Integer.valueOf(aVar.b()));
        w5 = a("apdra", bool);
        x5 = a("apdrfs", bool);
        y5 = a("apdrma", bool);
        z5 = a("apdrmd", bool);
        A5 = a("apdrfa", bool);
        B5 = a("apdrev", bool);
        C5 = a("apdrdi", bool);
        D5 = a("apdrrp", bool);
        E5 = a("server_timestamp_ms", 0L);
        F5 = a("device_timestamp_ms", 0L);
        G5 = a("gzip_min_length", 0);
        H5 = a("gzip_encoding_default", bool);
        I5 = a("fetch_settings_gzip", bool);
        J5 = a("device_init_gzip", bool);
        K5 = a("fetch_ad_gzip", bool);
        L5 = a("event_tracking_gzip", bool);
        M5 = a("reward_postback_gzip", bool);
        N5 = a("handle_render_process_gone", bool2);
        O5 = a("rworpg", bool2);
        P5 = a("fdadaomr", bool2);
        Q5 = a("teorpc", bool);
        R5 = a("set_webview_render_process_client", bool);
        S5 = a("disable_webview_hardware_acceleration", bool);
        T5 = a("anr_detection_enabled", bool);
        U5 = a("anr_trigger_millis", 4000L);
        V5 = a("anr_touch_millis", Long.valueOf(C.DEFAULT_MAX_SEEK_TO_PREVIOUS_POSITION_MS));
        W5 = a("anr_check_millis", Long.valueOf(C.DEFAULT_MAX_SEEK_TO_PREVIOUS_POSITION_MS));
        X5 = a("uobid", bool2);
        Y5 = a("bvde", bool);
        Z5 = a("bvdidm", 1000L);
        a6 = a("bvdim", 4000L);
        b6 = a("bvdrs", 10);
        c6 = a("bvdct", 230);
        d6 = a("bvdict", 3);
        e6 = a("bvad", bool);
        f6 = a("bvebb", bool2);
        g6 = a("bvscb", bool2);
        h6 = a("bvlmtb", -1L);
        i6 = a("dwvvb", bool);
        j6 = a("stcpc", bool2);
        k6 = a("stcic", bool2);
        l6 = a("clacaf", bool);
        m6 = a("qjscwwvl", bool);
        n6 = a("web_contents_debugging_enabled", bool);
        o6 = a("fcioiauiidb", bool2);
        p6 = a("teouauiidb", bool2);
        q6 = a("usc", bool);
        r6 = a("should_apply_web_view_settings_to_web_view_button", bool);
        s6 = a("config_consent_dialog_state", "unknown");
        t6 = a("country_code", "");
        u6 = a("consent_flow_doc_url", "https://developers.applovin.com/en/android/overview/terms-and-privacy-policy-flow");
        v6 = a("consent_flow_unity_doc_url", "https://developers.applovin.com/en/unity/overview/terms-and-privacy-policy-flow");
        w6 = a("cfadtml", 20);
        x6 = a("enable_custom_tabs_service", bool);
        y6 = a("custom_tabs_service_reconnect_delay_ms", -1L);
        z6 = a("ps_etr", bool);
        A6 = a("ps_tri_ms", Long.valueOf(timeUnit3.toMillis(7L)));
        B6 = a("ps_ftri_ms", -1L);
        C6 = a("ps_sroftr", bool);
        D6 = a("ps_sroftrof", bool);
        E6 = a("communicator_enabled", bool2);
        F6 = a("adse", bool2);
    }

    public oj(String str, Object obj) {
        if (str == null) {
            throw new IllegalArgumentException("No name specified");
        }
        if (obj != null) {
            this.f760a = str;
            this.b = obj;
            return;
        }
        throw new IllegalArgumentException("No default value specified");
    }

    public String b() {
        return this.f760a;
    }

    public Object a(Object obj) {
        return this.b.getClass().cast(obj);
    }

    @Override // java.lang.Comparable
    public int compareTo(Object obj) {
        if (!(obj instanceof oj)) {
            return 0;
        }
        return this.f760a.compareTo(((oj) obj).b());
    }

    public Object a() {
        return this.b;
    }

    protected static oj a(String str, Object obj) {
        if (obj != null) {
            if (c.contains(obj.getClass())) {
                oj ojVar = new oj(str, obj);
                Map map = d;
                if (!map.containsKey(str)) {
                    map.put(str, ojVar);
                    return ojVar;
                }
                throw new IllegalArgumentException("Setting has already been used: " + str);
            }
            throw new IllegalArgumentException("Unsupported value type: " + obj.getClass());
        }
        throw new IllegalArgumentException("No default value specified");
    }
}
