package com.applovin.impl;

import com.applovin.impl.uj;
import java.util.Arrays;
import java.util.concurrent.TimeUnit;

/* loaded from: classes.dex */
public abstract class qe extends oj {
    public static final oj A7;
    public static final oj B7;
    public static final oj C7;
    public static final oj D7;
    public static final oj E7;
    public static final oj F7;
    public static final oj G6 = oj.a("afi", "");
    public static final oj G7;
    public static final oj H6;
    public static final oj H7;
    public static final oj I6;
    public static final oj I7;
    public static final oj J6;
    public static final oj J7;
    public static final oj K6;
    public static final oj K7;
    public static final oj L6;
    public static final oj L7;
    public static final oj M6;
    public static final oj M7;
    public static final oj N6;
    public static final oj N7;
    public static final oj O6;
    public static final oj O7;
    public static final oj P6;
    public static final oj P7;
    public static final oj Q6;
    public static final oj R6;
    public static final oj S6;
    public static final oj T6;
    public static final oj U6;
    public static final oj V6;
    public static final oj W6;
    public static final oj X6;
    public static final oj Y6;
    public static final oj Z6;
    public static final oj a7;
    public static final oj b7;
    public static final oj c7;
    public static final oj d7;
    public static final oj e7;
    public static final oj f7;
    public static final oj g7;
    public static final oj h7;
    public static final oj i7;
    public static final oj j7;
    public static final oj k7;
    public static final oj l7;
    public static final oj m7;
    public static final oj n7;
    public static final oj o7;
    public static final oj p7;
    public static final oj q7;
    public static final oj r7;
    public static final oj s7;
    public static final oj t7;
    public static final oj u7;
    public static final oj v7;
    public static final oj w7;
    public static final oj x7;
    public static final oj y7;
    public static final oj z7;

    static {
        TimeUnit timeUnit = TimeUnit.SECONDS;
        H6 = oj.a("afi_ms", Long.valueOf(timeUnit.toMillis(5L)));
        I6 = oj.a("mediation_endpoint", "https://ms.applovin.com/");
        J6 = oj.a("mediation_backup_endpoint", "https://ms.applvn.com/");
        K6 = oj.a("fetch_next_ad_retry_delay_ms", Long.valueOf(timeUnit.toMillis(2L)));
        L6 = oj.a("fetch_next_ad_timeout_ms", Long.valueOf(timeUnit.toMillis(30L)));
        M6 = oj.a("fetch_mediation_debugger_info_timeout_ms", Long.valueOf(timeUnit.toMillis(7L)));
        Boolean bool = Boolean.TRUE;
        N6 = oj.a("auto_init_mediation_debugger", bool);
        O6 = oj.a("postback_macros", "{\"{MCODE}\":\"mcode\",\"{BCODE}\":\"bcode\",\"{ICODE}\":\"icode\",\"{SCODE}\":\"scode\"}");
        P6 = oj.a("max_signal_provider_latency_ms", Long.valueOf(timeUnit.toMillis(30L)));
        Boolean bool2 = Boolean.FALSE;
        Q6 = oj.a("fix_signal_collection_timeout_signal_providers_count", bool2);
        R6 = oj.a("default_adapter_timeout_ms", Long.valueOf(timeUnit.toMillis(10L)));
        S6 = oj.a("ad_refresh_ms", Long.valueOf(timeUnit.toMillis(30L)));
        T6 = oj.a("ad_load_failure_refresh_ms", Long.valueOf(timeUnit.toMillis(30L)));
        U6 = oj.a("ad_load_failure_refresh_ignore_error_codes", "204");
        V6 = oj.a("refresh_ad_on_app_resume_elapsed_threshold_ms", 0L);
        W6 = oj.a("refresh_ad_view_timer_responds_to_background", bool);
        X6 = oj.a("refresh_ad_view_timer_responds_to_store_kit", bool);
        Y6 = oj.a("refresh_ad_view_timer_responds_to_window_visibility_changed", bool2);
        Z6 = oj.a("avrsponse", bool2);
        a7 = oj.a("allow_pause_auto_refresh_immediately", bool2);
        b7 = oj.a("fullscreen_display_delay_ms", 0L);
        c7 = oj.a("susaode", bool2);
        d7 = oj.a("ahdm", 500L);
        e7 = oj.a("ad_view_refresh_precache_request_viewability_undesired_flags", 246L);
        f7 = oj.a("ad_view_refresh_precache_request_enabled", bool);
        g7 = oj.a("fabsiaif", bool2);
        h7 = oj.a("famttl_ms", 0L);
        i7 = oj.a("signal_expiration_ms", -1L);
        j7 = oj.a("signal_cache_level", Integer.valueOf(uj.b.AD_FORMAT.ordinal()));
        TimeUnit timeUnit2 = TimeUnit.HOURS;
        k7 = oj.a("ad_expiration_ms", Long.valueOf(timeUnit2.toMillis(4L)));
        l7 = oj.a("native_ad_expiration_ms", Long.valueOf(timeUnit2.toMillis(4L)));
        m7 = oj.a("rena", bool);
        n7 = oj.a("fullscreen_ad_displayed_timeout_ms", -1L);
        o7 = oj.a("freast_ms", -1L);
        p7 = oj.a("ad_hidden_timeout_ms", -1L);
        q7 = oj.a("schedule_ad_hidden_on_ad_dismiss", bool2);
        r7 = oj.a("schedule_ad_hidden_on_single_task_app_relaunch", bool2);
        s7 = oj.a("ad_hidden_on_ad_dismiss_callback_delay_ms", Long.valueOf(timeUnit.toMillis(1L)));
        t7 = oj.a("proe", bool2);
        u7 = oj.a("mute_state", 2);
        v7 = oj.a("saf", "");
        w7 = oj.a("saui", "");
        x7 = oj.a("mra", -1);
        y7 = oj.a("mra_af", "INTER,REWARDED,REWARDED_INTER,BANNER,LEADER,MREC");
        z7 = oj.a("svadfr", bool2);
        A7 = oj.a("fadiafase", bool);
        B7 = oj.a("fadwvcv", bool);
        C7 = oj.a("bfarud", bool2);
        D7 = oj.a("inacc", Boolean.valueOf(zp.b(Arrays.asList("com.textmeinc.textme", "com.textmeinc.freetone", "com.textmeinc.textme3", "com.jaumo", "com.jaumo.casual", "com.pinkapp", "com.jaumo.mature", "com.jaumo.prime", "com.jaumo.gay", "com.jaumo.lesbian"))));
        E7 = oj.a("pbataipaf", "");
        F7 = oj.a("bwt_ms", Long.valueOf(timeUnit.toMillis(30L)));
        G7 = oj.a("twt_ms", Long.valueOf(timeUnit.toMillis(30L)));
        H7 = oj.a("adiets_sec", Long.valueOf(TimeUnit.MINUTES.toSeconds(1L)));
        I7 = oj.a("ssasiimp", bool2);
        J7 = oj.a("faomq", bool2);
        K7 = oj.a("sppdater", bool2);
        L7 = oj.a("siflcfbt", bool2);
        M7 = oj.a("uabta", bool2);
        N7 = oj.a("fetch_mediated_ad_gzip", bool);
        O7 = oj.a("max_postback_gzip", bool);
        P7 = oj.a("remove_ad_view_before_destroy", bool);
    }
}
